name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest    
    
    env: 
        REACT_APP_MARVEL_API_PRIVATE_KEY: ${{ secrets.REACT_APP_MARVEL_API_PRIVATE_KEY }}
        REACT_APP_MARVEL_API_PUBLIC_KEY: ${{ secrets.REACT_APP_MARVEL_API_PUBLIC_KEY }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Test 
        run: |
          yarn test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build